name: Waka Readme

on:
  schedule:
    # Expected to be run at 3:00 AM Beijing Time
    - cron: '0 11 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: pyxherb/pyxherb@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
